.PHONY: clean All

All:
	@echo "----------Building project:[ 01_Basics - Debug ]----------"
	@cd "/home/abhishek/Desktop/C++/Opencv/01_Basics/01_Basics" && "$(MAKE)" -f  "01_Basics.mk"
clean:
	@echo "----------Cleaning project:[ 01_Basics - Debug ]----------"
	@cd "/home/abhishek/Desktop/C++/Opencv/01_Basics/01_Basics" && "$(MAKE)" -f  "01_Basics.mk" clean
